In [1]:
#ata integration
import pandas as pd
import numpy as np

In [3]:
#load data
Kota = pd.read_csv (r'Daftar Kota.csv')
Ikan = pd.read_csv(r'Daftar Ikan Tambak.csv')
Kota

    ID    KABUPATEN/KOTA
0    1             TUBAN
1    2          LAMONGAN
2    3            GRESIK
3    4     KOTA SURABAYA
4    5         BANGKALAN
5    6           SAMPANG
6    7         PAMEKASAN
7    8           SUMENEP
8    9          SIDOARJO
9   10          PASURUAN
10  11     KOTA PASURUAN
11  12       PROBOLINGGO
12  13  KOTA PROBOLINGGO
13  14         SITUBONDO
14  15        BANYUWANGI
15  16            JEMBER
16  17          LUMAJANG
17  18            MALANG
18  19            BLITAR
19  20       TULUNGAGUNG
20  21        TRENGGALEK
21  22           PACITAN
22  23           MAGETAN
23  24          PONOROGO
24  25             NGAWI
25  26        BOJONEGORO
26  27           NGANJUK
27  28            MADIUN
28  29       KOTA MADIUN
29  30           JOMBANG
30  31            KEDIRI
31  32       KOTA KEDIRI
32  33         MOJOKERTO
33  34    KOTA MOJOKERTO
34  35       KOTA MALANG
35  36            BLITAR
36  37       KOTA BLITAR
37  38         BONDOWOSO
38  39              BATU

In [4]:
Ikan

    ID  Kerapu  Mujair  Tawes  Kakap  Bandeng     Nila  Belanak  Lainnya
0    1    23.6   147.3      0    0.0   1039.1     27.4      0.0      0.6
1    2   306.6   131.2      0    0.0    738.6    127.0      0.0     75.8
2    3    66.7  1734.9      0    0.0  39545.5      0.0    695.6    487.7
3    4     0.0     0.0      0    0.0   4618.7      0.0      0.0    501.3
4    5     0.0   307.2      0  264.8    723.8      0.0    400.0      0.0
5    6     0.0   633.5      0    0.0   2140.0      0.0    418.0    437.0
6    7     0.0     0.0      0    0.0      0.0      0.0      0.0     37.8
7    8     0.0   149.1      0    0.0    368.8      6.5    143.7     47.6
8    9     0.0  3748.2      0    0.0  34561.9  17983.1      0.0   1604.1
9   10     0.0  1506.9      0    0.0   4518.7    517.7      0.0    394.3
10  11     0.0     5.5      0    3.0    494.3      0.0      0.0      7.1
11  12     3.0   131.4      0    2.0   1465.8    153.6     75.3      9.7
12  13     0.0    15.9      0    1.2    143.6      7.5      2.7      0.0
13  14     0.0     7.4      0    0.0      5.6      5.1      0.0      0.0
14  15    75.6    25.6      0  131.3    141.1    635.9     11.0     58.1
15  16     0.0     0.0      0    0.0      8.8      0.0      0.0      0.0
16  17     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
17  18     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
18  19     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
19  20     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
20  21     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
21  22     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
22  23     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
23  24     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
24  25     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
25  26     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
26  27     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
27  28     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
28  29     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
29  30     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
30  31     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
31  32     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
32  33     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
33  34     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
34  35     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
35  36     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
36  37     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
37  38     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0
38  39     0.0     0.0      0    0.0      0.0      0.0      0.0      0.0

In [6]:
#merge data based on ID
data = pd.merge(Kota, Ikan, on='ID')
data

,ID,KABUPATEN/KOTA,Kerapu,Mujair,Tawes,Kakap,Bandeng,Nila,Belanak,Lainnya
0,1,TUBAN,23.6,147.3,0,0.0,1039.1,27.4,0.0,0.6
1,2,LAMONGAN,306.6,131.2,0,0.0,738.6,127.0,0.0,75.8
2,3,GRESIK,66.7,1734.9,0,0.0,39545.5,0.0,695.6,487.7
3,4,KOTA SURABAYA,0.0,0.0,0,0.0,4618.7,0.0,0.0,501.3
4,5,BANGKALAN,0.0,307.2,0,264.8,723.8,0.0,400.0,0.0
5,6,SAMPANG,0.0,633.5,0,0.0,2140.0,0.0,418.0,437.0
6,7,PAMEKASAN,0.0,0.0,0,0.0,0.0,0.0,0.0,37.8
7,8,SUMENEP,0.0,149.1,0,0.0,368.8,6.5,143.7,47.6
8,9,SIDOARJO,0.0,3748.2,0,0.0,34561.9,17983.1,0.0,1604.1
9,10,PASURUAN,0.0,1506.9,0,0.0,4518.7,517.7,0.0,394.3
10,11,KOTA PASURUAN,0.0,5.5,0,3.0,494.3,0.0,0.0,7.1
11,12,PROBOLINGGO,3.0,131.4,0,2.0,1465.8,153.6,75.3,9.7
12,13,KOTA PROBOLINGGO,0.0,15.9,0,1.2,143.6,7.5,2.7,0.0
13,14,SITUBONDO,0.0,7.4,0,0.0,5.6,5.1,0.0,0.0
14,15,BANYUWANGI,75.6,25.6,0,131.3,141.1,635.9,11.0,58.1
15,16,JEMBER,0.0,0.0,0,0.0,8.8,0.0,0.0,0.0
16,17,LUMAJANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
17,18,MALANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
18,19,BLITAR,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
19,20,TULUNGAGUNG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
20,21,TRENGGALEK,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
21,22,PACITAN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
22,23,MAGETAN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
23,24,PONOROGO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
24,25,NGAWI,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
25,26,BOJONEGORO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
26,27,NGANJUK,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
27,28,MADIUN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
28,29,KOTA MADIUN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
29,30,JOMBANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
30,31,KEDIRI,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
31,32,KOTA KEDIRI,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
32,33,MOJOKERTO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
33,34,KOTA MOJOKERTO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
34,35,KOTA MALANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
35,36,BLITAR,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
36,37,KOTA BLITAR,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
37,38,BONDOWOSO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
38,39,BATU,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0

In [10]:
#insert new colomn
data['Subtotal'] = (data['Kerapu']+data['Mujair']+data['Tawes']+data['Kakap']+data['Bandeng']+data['Nila']+data['Belanak']+data['Lainnya'])
data

,ID,KABUPATEN/KOTA,Kerapu,Mujair,Tawes,Kakap,Bandeng,Nila,Belanak,Lainnya,Subtotal
0,1,TUBAN,23.6,147.3,0,0.0,1039.1,27.4,0.0,0.6,1238.0
1,2,LAMONGAN,306.6,131.2,0,0.0,738.6,127.0,0.0,75.8,1379.2
2,3,GRESIK,66.7,1734.9,0,0.0,39545.5,0.0,695.6,487.7,42530.4
3,4,KOTA SURABAYA,0.0,0.0,0,0.0,4618.7,0.0,0.0,501.3,5120.0
4,5,BANGKALAN,0.0,307.2,0,264.8,723.8,0.0,400.0,0.0,1695.8
5,6,SAMPANG,0.0,633.5,0,0.0,2140.0,0.0,418.0,437.0,3628.5
6,7,PAMEKASAN,0.0,0.0,0,0.0,0.0,0.0,0.0,37.8,37.8
7,8,SUMENEP,0.0,149.1,0,0.0,368.8,6.5,143.7,47.6,715.7
8,9,SIDOARJO,0.0,3748.2,0,0.0,34561.9,17983.1,0.0,1604.1,57897.3
9,10,PASURUAN,0.0,1506.9,0,0.0,4518.7,517.7,0.0,394.3,6937.6
10,11,KOTA PASURUAN,0.0,5.5,0,3.0,494.3,0.0,0.0,7.1,509.9
11,12,PROBOLINGGO,3.0,131.4,0,2.0,1465.8,153.6,75.3,9.7,1840.8
12,13,KOTA PROBOLINGGO,0.0,15.9,0,1.2,143.6,7.5,2.7,0.0,170.9
13,14,SITUBONDO,0.0,7.4,0,0.0,5.6,5.1,0.0,0.0,18.1
14,15,BANYUWANGI,75.6,25.6,0,131.3,141.1,635.9,11.0,58.1,1078.6
15,16,JEMBER,0.0,0.0,0,0.0,8.8,0.0,0.0,0.0,8.8
16,17,LUMAJANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,MALANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
18,19,BLITAR,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,20,TULUNGAGUNG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
20,21,TRENGGALEK,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
21,22,PACITAN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
22,23,MAGETAN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
23,24,PONOROGO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
24,25,NGAWI,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,26,BOJONEGORO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,27,NGANJUK,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
27,28,MADIUN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,29,KOTA MADIUN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
29,30,JOMBANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
30,31,KEDIRI,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
31,32,KOTA KEDIRI,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
32,33,MOJOKERTO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
33,34,KOTA MOJOKERTO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
34,35,KOTA MALANG,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
35,36,BLITAR,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
36,37,KOTA BLITAR,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
37,38,BONDOWOSO,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
38,39,BATU,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0